### ISSUE TITLE
Unable to login due to fatal error

### ISSUE THREAD

**Issue by HiddenKn** [phpBB-Studio/DiscordOAuth2light#2]
**Describe the bug**
When trying to login or link accounts I get a FATAL ERROR.

**To Reproduce**
1. Setup plugin in admin control panel.
2. Log out
3. Try logging in using the discord icon
4. Get send to https://[MYDOMAINHERE].com/forum/ucp.php?mode=login&login=external&oauth_service=discord
5. See error: 
`
Fatal error: Uncaught Exception: AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED in /var/www/html/forum/phpbb/auth/provider/oauth/oauth.php:402 Stack trace: #0 /var/www/html/forum/phpbb/auth/provider/oauth/oauth.php(211): phpbb\auth\provider\oauth\oauth->get_service('discord', Object(phpbb\auth\provider\oauth\token_storage), Array, 'mode=login&logi...', Array) #1 /var/www/html/forum/phpbb/auth/auth.php(949): phpbb\auth\provider\oauth\oauth->login('', '') #2 /var/www/html/forum/includes/functions.php(2377): phpbb\auth\auth->login('', '', false, 1, 0) #3 /var/www/html/forum/ucp.php(90): login_box('index.php') #4 {main} thrown in /var/www/html/forum/phpbb/auth/provider/oauth/oauth.php on line 402
`

**Expected behavior**
I expected to be forwarded to Discord to provide access to my account.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
I used this PR while testing: https://github.com/phpBB-Studio/DiscordOAuth2light/pull/1

**Comment by 3D-I** [comment]
Unable to reproduce in localhost.

Used a virgin 3.2.8-rc1, I will test live today to confirm.

**Comment by 3D-I** [comment]
Ok, on my live server I see an error 500, thanks for reporting.

**Comment by 3D-I** [comment]
Should be fixed now.
