### ISSUE TITLE
Discord OAuth 2 light does not show in extension manager

### ISSUE THREAD

**Issue by NeonOdyssey** [phpBB-Studio/DiscordOAuth2light#4]
**Describe the bug**
Discord OAuth 2 light does not show in the extension manager

**To Reproduce**
1. Go to ACP
2. Click on EXTENSIONS
3. The extension isn't visible to configure

**Expected behavior**
Should expect to see the extension so I can configure and input my client id and secret

**Screenshots**
![image](https://user-images.githubusercontent.com/45792245/66261904-98d63d80-e7cd-11e9-80cc-4561fa374e6b.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Browser: Chrome, Edge, Firefox
 - Version: PHPBB 3.2.8

**Smartphone (please complete the following information):**
 - Device: Samsung Note 10+ 5G
 - OS: Andriod 10
 - Browser: Chrome

**Comment by 3D-I** [comment]
There is nothing to configure there since, there is not an acp panel for this extension.

Please read the instructions: https://github.com/phpBB-Studio/DiscordOAuth2light/tree/master/docs#application-settings

OAuths are to configure elsewhere like

`ACP / Client communication / Authentication`
