### ISSUE TITLE
OAuth Service not created message

### ISSUE THREAD

**Issue by phoenixegmh** [phpBB-Studio/DiscordOAuth2light#5]
**Describe the bug**
When trying to log in / link Discord account to phpBB after install, receiving a "OAuth service not created" message in phpBB.

**Screenshots**
![image](https://user-images.githubusercontent.com/62211163/122559397-2c4db180-d037-11eb-95fa-65959154933c.png)
![image](https://user-images.githubusercontent.com/62211163/122559470-47202600-d037-11eb-8dab-f21783ffef3c.png)
![image](https://user-images.githubusercontent.com/62211163/122559540-6323c780-d037-11eb-9642-1f9fb780d73d.png)
![image](https://user-images.githubusercontent.com/62211163/122559648-85b5e080-d037-11eb-95da-a9317737ce9d.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome & Brave
 - 
**Additional context**
Believe installed as per instructions

**Comment by 3D-I** [comment]
Use the download package from our site: https://phpbbstudio.com/extensions/discord-oauth2-light
